sell:
  - "&b&lServer&f&lMC"
  - "{name} &7[x{amount}]"
  - "&c&lS &f${sell}"
buy:
  - "&b&lServer&f&lMC"
  - "{name} &7[x{amount}]"
  - "&a&lB &f${buy}"
sell-buy:
  - "&b&lServer&f&lMC"
  - "{name} &7[x{amount}]"
  - "&a&lB &f${buy} &7| &c&lS &f${sell}"